### ISSUE TITLE
some problem with the swiftpm

### ISSUE THREAD

**Issue by linkdeep** [way-to-code/git-macOS#2]
A Package.swift manifest file must begin with the string // swift-tools-version:

**Comment by linkdeep** [comment]
there is some other issue the I install it with swiftpm. I think you could try it first.
by the way, nice code!

**Comment by way-to-code** [comment]
Thanks for your report! 

Swift package manager was not my initial goal, so I even have not tested it. Anyway, it should now work starting from `1.6.2` version.
