### ISSUE TITLE
Intercept the end of the cloning

### ISSUE THREAD

**Issue by Angelk90** [way-to-code/git-macOS#9]
Hi @way-to-code , there is a way to intercept the end of the cloning?

**Comment by way-to-code** [comment]
Hey!  @Angelk90 

When the clone method is finished execution, this is the end of the clone process. The method blocks the executing thread until all background tasks are finished. All other methods in the framework work similar way.

```swift
do {
    try clone(atPath: clonePath, options: options)
    // The clone operation has been finished successfully
} catch {
    // The clone operation has been fallen with error
    throw error
}
```

**Comment by Angelk90** [comment]
@way-to-code : Thx, I understand.
